### ISSUE TITLE
2.2.0.rc.0 seems to break dependency resolving

### ISSUE THREAD

**Issue by tkornai** [chef/mixlib-shellout#105]
Since the rc release of 2.2.0 our chef installation breaks with the following:

2015-09-01 15:30:21,682 [INFO] Installing chef version 12.4.0 via gem
2015-09-01 15:30:23,667 [ERROR] Gem failed. Output: ERROR:  While executing gem ... (Gem::Dependency
Error)
    Unresolved dependency found during sorting - mixlib-shellout (~> 2.0) (requested by ohai-8.5.1)

**Comment by jaym** [comment]
ugh, this is annoying. I forgot about the published gems

**Comment by jaym** [comment]
going to yank the gem

**Comment by jaym** [comment]
can you give it another go, the gems have been yanked

**Comment by tkornai** [comment]
Sure, will get back to you in ~10 minutes.

**Comment by tkornai** [comment]
Still the same issue.

**Comment by jaym** [comment]
yea, i'm getting the same issue.
It works fine if i instlal ohai first

**Comment by jaym** [comment]
probably caching issues, should work now

**Comment by tkornai** [comment]
It does, thanks for the quick fix!
