### ISSUE TITLE
mixlib-shellout requires Ruby version >= 1.9.3.

### ISSUE THREAD

**Issue by corecible** [chef/mixlib-shellout#115]
however ,my ruby version is 1.9.3.

sudo gem install mixlib-shellout
ERROR:  Error installing mixlib-shellout:
 mixlib-shellout requires Ruby version >= 1.9.3.

os is ubuntu 10.04.4 LTS .how to resolve it

**Comment by corecible** [comment]
I just tried  to install ruby 2.2.2, it reported the same mistakes.
test@ubuntu:~$ sudo gem install mixlib-shellout -V
GET http://rubygems.org/latest_specs.4.8.gz
302 Moved Temporarily
GET http://rubygems.global.ssl.fastly.net/latest_specs.4.8.gz
200 OK
GET https://ruby.taobao.org/latest_specs.4.8.gz
302 Moved Temporarily
GET https://rubygems-china.oss-cn-hangzhou.aliyuncs.com/latest_specs.4.8.gz
200 OK
GET https://ruby.taobao.org/quick/Marshal.4.8/mixlib-shellout-2.2.5.gemspec.rz
302 Moved Temporarily
GET https://rubygems-china.oss-cn-hangzhou.aliyuncs.com/quick/Marshal.4.8/mixlib-shellout-2.2.5.gemspec.rz
200 OK
GET http://rubygems.org/quick/Marshal.4.8/mixlib-shellout-2.2.5.gemspec.rz
302 Moved Temporarily
GET http://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/mixlib-shellout-2.2.5.gemspec.rz
200 OK
Installing gem mixlib-shellout-2.2.5
ERROR:  Error installing mixlib-shellout:
        mixlib-shellout requires Ruby version >= 1.9.3.
test@ubuntu:~$ 
test@ubuntu:~$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]

**Comment by corecible** [comment]
I installed  ruby  by rvm

**Comment by lamont-granquist** [comment]
check `which gem` and `which ruby`, since it looks like ruby is pointed at your rvm instance while gem is probably pointed at the /usr/bin/gem ruby 1.8.7 version.

we don't support ruby 1.8.7 and don't support ubuntu 10.04 any more, they're EOL.  ruby 1.8.7 is just broken at this point, and ubuntu 10.04 probably works but we don't explicitly support it at all.

**Comment by corecible** [comment]
thank you .
