### ISSUE TITLE
Array form of command passing doesn't work on Windows

### ISSUE THREAD

**Issue by coderanger** [chef/mixlib-shellout#125]
The windows backend assumes in several places that `command` is a string, but it can be an array too. The simplest fix would be to use `Shellwords.join` or something similar to convert to a string, but supporting the same semantics as unix would be nice. On unix, passing an array instead of a string bypasses the `/bin/sh -c` wrapper on the command which helps avoid bugs/security issues from injecting shell parsing/handling where it isn't expected.

**Comment by muffins** [comment]
+1 Spent some time digging around today for using command fragment arrays in our Chef recipes, and stumbled across this. Would be super nice if Windows behaved like Posix :)

**Comment by lamont-granquist** [comment]
Everyone wants this fixed, but I took a run at fixing it before and it broke specs and I could not figure out how to greenify them after working on them for hours.

The full nightmare that is quotes and the windows CLI is here:

https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/

**Comment by lamont-granquist** [comment]
Because of this problem core chef itself also constantly bleeds bugs about quoting command line arguments, this bug is still open not because nobody sees the point in it, but because it is Hard(tm).

**Comment by lamont-granquist** [comment]
fixed by #182
