### ISSUE TITLE
passing :valid_exit_codes option throws an error

### ISSUE THREAD

**Issue by ckehoe** [chef/mixlib-shellout#126]
I'm trying to get the output from running the git --version command. I do not want the program to exit if git is not installed on the system but simply not to set the installed_version variable. In order to do that I am trying to pass 127 as a valid exit code but i get the error in the output below. 

`cmd = Mixlib::ShellOut.new('git', '--version', :valid_exit_codes => [0, 127])`
`cmd.run_command`
`if cmd.stderr.empty? and !cmd.stdout.empty?`
  `installed_version = cmd.stdout.scan(/\d+/).join('.')`
`end`

/home/ckehoe/.gem/ruby/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout.rb:343:in `block in parse_options': option ':valid_exit_codes' is not a valid option for Mixlib::ShellOut (Mixlib::ShellOut::InvalidCommandOption)
	from /home/ckehoe/.gem/ruby/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout.rb:301:in `each'
	from /home/ckehoe/.gem/ruby/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout.rb:301:in `parse_options'
	from /home/ckehoe/.gem/ruby/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout.rb:177:in `initialize'
	from /home/ckehoe/test.rb:63:in `new'
	from /home/ckehoe/test.rb:63:in `valid_git_installation?'
	from /home/ckehoe/test.rb:80:in `<main>'

**Comment by ckehoe** [comment]
Okay looks like the problem was using :valid_exit_codes instead of :returns. Switching that out gets rid of the error but even passing the error code (127) still causes the command to fail and my script to stop:

/home/ckehoe/.gem/ruby/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:338:in `exec': No such file or directory - git (Errno::ENOENT)
	from /home/ckehoe/.gem/ruby/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:338:in `block in fork_subprocess'
	from /home/ckehoe/.gem/ruby/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:316:in `fork'
	from /home/ckehoe/.gem/ruby/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:316:in `fork_subprocess'
	from /home/ckehoe/.gem/ruby/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:93:in `run_command'
	from /home/ckehoe/.gem/ruby/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout.rb:259:in `run_command'
	from /home/ckehoe/test.rb:64:in `valid_git_installation?'
	from /home/ckehoe/test.rb:80:in `<main>'

**Comment by lamont-granquist** [comment]
yeah we don't support return codes from a failure to exec.  you'll need to `rescue Errno::ENOENT` from that.

probably not something that we'll ever bother to fix, feel free to submit a PR that implements it though if you disagree...
