### ISSUE TITLE
Timeout while running copy cookbook

### ISSUE THREAD

**Issue by pulpet112** [chef/mixlib-shellout#128]
Hi! I need to write a chef recipe which copy mounted folder [source folder] to another [direct folder]. 
I wrote this recipe:

> execute "copy" do
>           command ".#{node[some path in atribute]/copy.sh"
>           timeout 100
>           action :nothing
>         end
>         template "#{node[some path in atribute]/copy.sh" do
>             source "template.erb"
>             mode 0755
>             notifies :run, "execute[copy]", :immediately
>         end

The template is:

> sshpass -p <%= node['pass from attribute']%> scp -r -o StrictHostKeyChecking=no <%= node[client name from attribute]%>@[host]:/[source path] <%= node[direct path from attribute]%>

When i run my cookbook I receive in console:

```
Mixlib::ShellOut::CommandTimeout
--------------------------------
Command timed out after 100s:
Command exceeded allowed execution time, process terminated
---- Begin output of ./[path]/copy.sh ----
STDOUT:
STDERR: Killed by signal 1.
---- End output of ./tmp/devops.sh ----
Ran ./[path]/copy.sh returned

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/copy/recipes/default.rb
```

 ///code from recipe

```
Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/copy/recipes/default.rb:4:in `from_file'

execute("copy") do
  action [:nothing]
  retries 0
  retry_delay 2
  default_guard_interpreter :execute
  command "./[path]/copy.sh"
  backup 5
  returns 0
  timeout 100
  declared_type :execute
  cookbook_name "copy"
  recipe_name "default"
end

Platform:
---------
x86_64-linux
```

Running handlers:
[2016-07-19T14:35:17+02:00] ERROR: Running exception handlers
Running handlers complete
[2016-07-19T14:35:17+02:00] ERROR: Exception handlers complete
Chef Client failed. 3 resources updated in 02 minutes 02 seconds
[2016-07-19T14:35:17+02:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2016-07-19T14:35:17+02:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-07-19T14:35:17+02:00] ERROR: execute[devops](copy::default line 4) had an error: Mixlib::ShellOut::CommandTimeout: Command timed out after 100s:
Command exceeded allowed execution time, process terminated
---- Begin output of ./tmp/devops.sh ----
STDOUT:
STDERR: Killed by signal 1.
---- End output of ./tmp/devops.sh ----
Ran ./tmp/devops.sh returned
[2016-07-19T14:35:17+02:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

What is wrong?? I have no idea

**Comment by lamont-granquist** [comment]
well, this was misfiled under mixlib-shellout rather than chef/chef and it seems to be 6+ months old by now.

you've set a timeout on the execute resource which looks to have correctly fired and killed the job.

for some reason "devops.sh" (which looks to be what you're actually running and not copy.sh) is taking longer than 100 seconds -- either you didn't allow enough time for the files to copy or else my guess would be that its waiting for user input and you needed flags like `-oBatchMode=yes` for ssh -- but that gets into the area of "notabug" and really stackoverflow or irc would be better to ask those questions.
