### ISSUE TITLE
Allow live_stdin for interactive processes

### ISSUE THREAD

**Issue by zfjagann** [chef/mixlib-shellout#138]
I'd like to add support for `live_stdin` to allow passing an IO object as stdin to the called process (similar to `live_stdout` and `live_stderr`).

I wanted to file this an issue before doing the ground work to make sure this was a feature you guys want.
I'm happy to put in a PR for it if you think it's useful. If not, I can find a different way to solve the issue I'm having.

## Details about my use-case

I have a ruby script which does some setup and tear-down for a chef-client run (things like setting environment variables, merging json attributes files, moving around logs etc.). It invokes chef-client using Mixlib::Shellout.

I'd like to modify it to be able to drop to a chef-shell instead of invoking chef-client. This way the setup/teardown is re-used and the chef-shell is invoked in the same context as a chef-client would be.
The easiest way to do this would just be to swap chef-client for chef-shell in the command (removing any arguments that are chef-client exclusive).

The issue is that there's no way for me to pass the stdin from the wrapper script to the chef-shell process, so the chef-shell process starts, hits EOF on stdin, and quits.
I can pass it individual commands by modifying the wrapper script, but what I'd really like to get an interactive chef-shell.

**Comment by kamaradclimber** [comment]
I have about the same use case.

**Comment by kamaradclimber** [comment]
Is there any progress on that ticket?

**Comment by lamont-granquist** [comment]
we're clearly not prioritizing this and probably won't.
