### ISSUE TITLE
Chef recepe create Windows_Task throw Error "SystemCallError: Invalid access to memory location. - CreateProcessW"

### ISSUE THREAD

**Issue by vanessazou** [chef/mixlib-shellout#143]
Hi, 

We have chef running on 100 machines every 30mins and constantly see random instance failed on "SystemCallError: Invalid access to memory location. - CreateProcessW" error. Totally random no easy way to replicate this issue locally.

The recipe is to create a windows scheduled job:
  windows_task 'Schedule_Job' do
    action :create
    task_name 'Schedule_Job'
    command 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe C:\scripts\Schedule_Job.ps1'
    frequency :hourly
end

Error:
windows_task[Schedule_Job] (server::Schedule_Job line 28) had an error: SystemCallError: Invalid access to memory location. - CreateProcessW

I have googled how to fix this issue. But the following links ended up in no solution.
https://github.com/chef/mixlib-shellout/issues/111
https://bugs.ruby-lang.org/issues/11515

Could anyone help me or give me some insight why this happens?

Thank you
Vanessa

**Comment by lamont-granquist** [comment]
This bug should have been filed under the chef/chef project, this might have been fixed sometime in the past two years in the windows_task resource, but it would need to get revalidated as a current issue in chef-15 along with a better repro case.
