### ISSUE TITLE
Foodcritic whining for FC048: Prefer Mixlib::ShellOut:

### ISSUE THREAD

**Issue by santosgian28** [chef/mixlib-shellout#160]
My code block:
``` ruby
cmd = Mixlib::ShellOut.new("/usr/bin/echo test",
    user: (node['webhook_api']['app_username']).to_s)
    cmd.run_command
```
Then foodcritic stops whining when change to ```Mixlib::Shellout:``` but my code converge will fail.

Help.. Thank you

**Comment by coderanger** [comment]
This is not related to mixlib-shellout as a project, and I see you cross-filed this anyway.
