### ISSUE TITLE
Windows impersonation does not load user profile correctly

### ISSUE THREAD

**Issue by pbobov** [chef/mixlib-shellout#168]
Mixlib::ShellOut does not load user profile of the impersonated user account, so the user's environment variables such as USERNAME, USERPROFILE, TEMP, TMP, APPDATA, and LOCALAPPDATA still point to the parent process user name and directories.

To reproduce the problem use Mixlib::ShellOut to run windows .bat with single command `set` (that prints  values of the environment variables)  under as a different user.

Tested with Chef Client version 13.11.3.

**Comment by dayglojesus** [comment]
@pbobov I am investigating a similar issue -- Mixlib's behaviour when impersonating accounts is complicated...

Depending on the conditions, Mixlib will attempt one of three possible methods of execution:

- CreateProcessAsUser
- CreateProcessWithLogonW
- CreateProcess

In general, it seems that **a user's profile is never loaded** when:

1. the task uses `elevated: true` OR
2. Chef is running under the `LocalSystem` (`nt authority\system`) account OR
3. the task is executed from the "service windows station" OR
4. no `username` and `password` is supplied

If your Chef resource or call to `Mixlib::ShellOut` meets any of the above criteria then that would be ther reason. The biggest wrinkle appears to be this [MS documentation](https://docs.microsoft.com/en-ca/windows/desktop/api/winbase/nf-winbase-createprocesswithlogonw):

> *Windows XP with SP2,Windows Server 2003, or later:*You cannot call *CreateProcessWithLogonW* from a process that is running under the "LocalSystem" account, because the function uses the logon SID in the caller token, and the token for the "LocalSystem" account does not contain this SID. As an alternative, use the  [CreateProcessAsUser](https://msdn.microsoft.com/6b3f4dd9-500b-420e-804a-401a9e188be8)  and  [LogonUser](https://msdn.microsoft.com/a6d880a0-0aed-4bdb-89c9-4f667ecb510e) functions.

As such, Mixlib is forced to call `CreateProcessAsUser` which does not perform any automatic loading of user profiles (added in #149).

I believe I have a patch for this I can submit soon, but it would be helpful to know if what Imention above is true in your scenario.

**Comment by lamont-granquist** [comment]
closed by #177
