### ISSUE TITLE
Support no-tty and redirect stdout/stderr to file use cases

### ISSUE THREAD

**Issue by taqtiqa-mark** [chef/mixlib-shellout#192]
### Describe the Enhancement:

1. Use Chef resources in recipes that rely on shell command IO contents in a no-tty environment, e.g. Clouds, Dokken and other such use cases.
1. Run shells and have their output directed to files: e.g. [SO](https://stackoverflow.com/q/40352299/152860)

### Describe the Need:

1. Users who employ no-tty environments for production or testing (Dokken) can have resources that don't rely on `.stdout`, `.stderr` or `.stdin`
1. Users who want to pipe shell command output to file and process can do that naturally from `shell_out`

### Current Alternative

Issue chef/chef/issues/8855 suggests there is currently no alternative.  
In that issue, even with the proposed use of the `git ref-source --verify` exit-status to verify the reference exists, you need to read `.stdout` to return the reference SHA.  

A very common use case for shell scripts is to pipe the `stdout` or `stderr` to files for later processing.

### Can We Help You Implement This?:

Feedback on whether this would be accepted.
Feedback on the interface:
 - `fstdout`, `fstderr` (and `fstdin` if straight forward).  When these are set `stdout`, `stderr` (and `stdin`)
 - Default is textmode, but support a binmode (`rb` and `wb`)
 - Default encoding is UTF-8, but support this being set.

Any other suggestion, pointers, hints or tips would be appreciated.

**Comment by lamont-granquist** [comment]
There's already the live_stderr/live_stdout stuff which might work.  I don't know if that can be used to wire up /dev/null or not since we mostly use that for live-streaming output in the debug log for chef-client.  It is possible the only missing feature is stdin handling.

> Default is textmode, but support a binmode (rb and wb)

I wouldn't worry about that.

> Default encoding is UTF-8, but support this being set.

I would actively discourage worrying about that until someone has a use case that requires it.

**Comment by taqtiqa-mark** [comment]
Thanks @lamont-granquist . The `live_stderr`/`live_stdout` functionality does suffice. 

Closing this until it doesn't.
