### ISSUE TITLE
Test expecting Errno::EPIPE fails in ppc64el

### ISSUE THREAD

**Issue by lucaskanashiro** [chef/mixlib-shellout#204]
# Version:

3.0.9 (however, it is likely reproducible with 3.0.10)

# Environment:

* Debian unstable in a ppc64el virtual machine
* Ruby 2.7

# Scenario:

Run tests in a ppc64el virtual machine.

# Steps to Reproduce:

In a Debian unstable ppc64el VM with ruby 2.7 do:

1- Get the source code of mixlib-shellout
2- Run tests

or

1- Install mixlib-shellout gem
2- Execute irb: `$ irb -rmixlib/shellout`
3- Run the following command used in the failing test:
```
Mixlib::ShellOut.new('ruby -e "bad_ruby { [ } ]"', input: [ "f" * 20_000, "u" * 20_000, "f" * 20_000, "u" * 20_000 ].join("\n")).run_command
```

# Expected Result:

All the tests successfully passing.

# Actual Result:

The test below fails:

```
Failures:

  1) Mixlib::ShellOut when executing the command when handling the subprocess when subprocess closes prematurely with input data should raise error
     Failure/Error: expect { executed_cmd }.to raise_error(Errno::EPIPE)
       expected Errno::EPIPE but nothing was raised
     # ./spec/mixlib/shellout_spec.rb:1439:in `block (6 levels) in <top (required)>'

Finished in 36.01 seconds (files took 0.23986 seconds to load)
143 examples, 1 failure

Failed examples:

rspec ./spec/mixlib/shellout_spec.rb:1438 # Mixlib::ShellOut when executing the command when handling the subprocess when subprocess closes prematurely with input data should raise error
```

The test tries to run the command listed above (in the Steps to Reproduce section) but in ppc64el the `Errno::EPIPE` exception is not raised. Changing the test to something like this fixes the failure (basically `s/20_000/2_000_000/`):

```
        context "with input data" do
          let(:ruby_code) { "bad_ruby { [ } ]" }
          let(:options) { { input: input } }
          let(:input) { [ "f" * 2_000_000, "u" * 2_000_000, "f" * 2_000_000, "u" * 2_000_000 ].join(LINE_ENDING) }

          # Should the exception be handled?
          it "should raise error" do
            expect { executed_cmd }.to raise_error(Errno::EPIPE)
          end
        end
```

Which makes me think this might be an issue with the size of some buffers in ppc64el. It can close all the file descriptors on time and the `SIGPIPE` is not raised.

However, I am not quite sure if this kind of test belongs to this gem since it is not responsible for raising this exception, it is done by something lower level.

**Comment by matoro** [comment]
I also ran into this and determined that it is due to page size.

The problem does not show up on architectures with 4k page size:  amd64, arm64, mips, riscv, hppa

The problem does show up on architectures with larger page size:  ppc64 (64k, though it would presumably work with a 4k kernel), alpha (8k), sparc (8k), loong (16k)

Perhaps the appropriate solution is to multiply the input size by (page size / 4k)?
