### ISSUE TITLE
Add execution_time to Windows

### ISSUE THREAD

**Issue by HeyItsGilbert** [chef/mixlib-shellout#238]
### Describe the Enhancement:
After a shell out on Windows, the `execution_time` property is not available.

### Describe the Need:
Being able to track execution time could be desirable when troubleshooting issues.

### Current Alternative
Track time in the process maybe? Would be very ugly.

### Can We Help You Implement This?:
I have a PR coming.

**Comment by dafyddcrosby** [comment]
@tpowell-progress this issue can be closed (was fixed with #247)
