### ISSUE TITLE
set_user doesn't properly change process privileges.

### ISSUE THREAD

**Issue by glasschef** [chef/mixlib-shellout#59]
https://github.com/opscode/mixlib-shellout/blob/3b389790688adb1007b33476ec2e2b6111e26d76/lib/mixlib/shellout/unix.rb#L122

This will set the uid and guid of the process, but the privilege doesn't properly get changed.  Process::UID.change_privilege(uid) will do this correctly (on RedHat, at least) but documentation says it's not guaranteed on all platforms:  http://rdoc.info/stdlib/core/1.9.3/Process/UID

**Comment by lamont-granquist** [comment]
`with_login` in #78 should fix this?  reopen this if it doesn't.
