### ISSUE TITLE
Set supplementary groups by default, allow users to modify supplementary groups

### ISSUE THREAD

**Issue by stevendanna** [chef/mixlib-shellout#68]
In addition to the real and effective group ID of a process, every process has a list of supplementary groups IDs.  From the `credentials(7)` man page on Linux:

> Supplementary group IDs.  This is a set of additional group IDs that are used for permission checks when accessing files and other shared resources.  On Linux kernels before 2.6.4, a process can be a member of up to 32 supplementary groups; since kernel 2.6.4, a process can be a member of up to 65536 supplementary groups.  The call sysconf(_SC_NGROUPS_MAX) can be used to determine the number of supplementary  groups of which a process may be a member.  A process can obtain its set of supplementary group IDs using getgroups(2), and can modify the set using setgroups(2).

See the related Chef bug here: https://tickets.opscode.com/browse/CHEF-3510

Programs such as `sudo` and `su` typically set the list of supplementary groups to the groups of which the EUID is a member.

In C, the relevant system calls to modify the group list are `initgroups` and `setgroups`

In Ruby, the group list can be modified with the Process.groups= method.

**Comment by sean-horn** [comment]
Affected customer in 3656

**Comment by lamont-granquist** [comment]
`with_login` fixes are merged
