### ISSUE TITLE
CreateProcessWithLogonW returns 0xC0000142

### ISSUE THREAD

**Issue by EasyAsABC123** [chef/mixlib-shellout#71]
valid username/password/domain

doesn't break with local machine script only on chef run

**Comment by ksubrama** [comment]
Related to https://github.com/chef/chef-dk/issues/482

**Comment by juliandunn** [comment]
Has this been closed by https://github.com/chef/mixlib-shellout/pull/107 ?

**Comment by ksubrama** [comment]
Oh no :(  It's https://github.com/djberg96/win32-process/issues/19 striking again.  The above comment about being related to chefdk-482 was incorrect.

**Comment by ksubrama** [comment]
We need to wait for an upstream fix (he's very responsive - so it shouldn't take long).  Once it has been released, the new version should be able to satisfy the version pin here, but I can also conservatively bump the version pin to ensure that the bug fix is being picked up.

**Comment by ksubrama** [comment]
Fixed upstream in https://github.com/djberg96/win32-process/commit/4babb9e410fe68949bc03ee262aa67927637dd23
