### ISSUE TITLE
DEFAULT_READ_TIMEOUT should be exposed higher

### ISSUE THREAD

**Issue by scassiba** [chef/mixlib-shellout#89]
Consider this a feature request. Currently, Mixlib::Shellout will kill a long running command after 600 seconds (see: https://github.com/chef/mixlib-shellout/blob/master/lib/mixlib/shellout.rb#L29).

In order to account for long running compiles during Chef runs or downloads, (vagrant box add, for example) it might make sense to expose DEFAULT_READ_TIMEOUT as an ENV variable so that the user can configure it to suit their needs without having to go hacking the gems that call shell_out().

**Comment by j4y** [comment]
it's configurable in that the caller needs to specify a timeout.  review these lines:

https://github.com/chef/mixlib-shellout/blob/master/lib/mixlib/shellout.rb#L306

https://github.com/chef/mixlib-shellout/blob/master/lib/mixlib/shellout.rb#L208

**Comment by scassiba** [comment]
That's fine and all, but the end user shouldn't go hacking away at something like chef-provisioning-vagrant just to tell Mixlib::Shellout to knock it off.

I understand that it can be configured via shell_out(), but that's not what this is about. I shouldn't need to go changing shell_out() just so it doesn't kill an in-flight download or compile that takes 1200 seconds instead of 600 seconds.

**Comment by lamont-granquist** [comment]
chef-provisioning-vagrant needs to explicitly expose this as a tweakable.
