### ISSUE TITLE
Interactive shells cause shellout to hang after previous commit.

### ISSUE THREAD

**Issue by jekriske** [chef/mixlib-shellout#93]
The change to  lib/mixlib/shellout/unix.rb in this commit:
https://github.com/chef/mixlib-shellout/commit/1a1154e864c6b3e230ae9380c7178bf36a6958ca#diff-ad684ea44a04ba1763d515eb5e7a374a

breaks interactive shells, see:
https://github.com/chef/chef/issues/2742
https://github.com/chef/chef/issues/3189

Reverting the change corrects the issue. All revisions of chef client 12 are affected by this bug.

**Comment by lamont-granquist** [comment]
fun, so setsid() clears the controlling tty, and replacing that with setpgrp broke that.  looks like the ioctl TIOCNOTTY will also drop the controlling terminal, but everyone suggests using setsid() instead.

**Comment by lamont-granquist** [comment]
Yeah, looks like we're doing too much work to do getpgid.  We can just call setsid() in the child and then the pgid and session of the child are set to the pid so we can just `kill -pid` and we'll magically get the right pgid without having to call getpgid.  Then the whole silly AIX getpgid issue goes away.
