### ISSUE TITLE
Exceptions should share a common parent

### ISSUE THREAD

**Issue by docwhat** [chef/mixlib-shellout#98]
The [shellout exceptions](https://github.com/chef/mixlib-shellout/blob/master/lib/mixlib/shellout/exceptions.rb#L3-L5) should all share a common parent for ease of rescue.

e.g.

~~~ ruby
module Mixlib
  class ShellOut
    class Error < RuntimeError; end
    class ShellCommandFailed < Error; end
    class CommandTimeout < Error; end
    class InvalidCommandOption < Error; end
  end
end
~~~

This allows code like...

~~~ ruby
begin
  Mixlib::ShellOut.new('some command').run_command
rescue Mixlib::ShellOut::Error => err
  puts "Whups! While running 'some command' I got #{err}"
  raise
end
~~~

**Comment by lamont-granquist** [comment]
This is a fine idea, but probably won't happen without code.

**Comment by lamont-granquist** [comment]
coming up on 10 months, closing without prejudice, anyone can ressurect with a PR

**Comment by docwhat** [comment]
I don't have permission to re-open this, but PR #116 has the fix.

**Comment by scalp42** [comment]
@lamont-granquist looks like a PR exists https://github.com/chef/mixlib-shellout/pull/116
